-- Expanded phone/tablet brand catalog for faster purchase entry.
-- Catalog values are editable later through the existing model-spec workflow.
do $$
declare v_brand_id uuid; v_model_id uuid; v_name text;
begin
  select id into v_brand_id from public.brands where lower(name)=lower('Apple') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Apple','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['iPad Pro 13-inch (M5)','iPad Pro 11-inch (M5)','iPad Air 13-inch (M4)','iPad Air 11-inch (M4)','iPad (A16)','iPad mini (A17 Pro)','iPad Pro 13-inch (M4)','iPad Pro 11-inch (M4)','iPad Pro 12.9-inch (6th generation)','iPad Pro 12.9-inch (5th generation)','iPad Pro 12.9-inch (4th generation)','iPad Pro 12.9-inch (3rd generation)','iPad Pro 12.9-inch (2nd generation)','iPad Pro 12.9-inch (1st generation)','iPad Pro 11-inch (4th generation)','iPad Pro 11-inch (3rd generation)','iPad Pro 11-inch (2nd generation)','iPad Pro 11-inch (1st generation)','iPad Pro 10.5-inch','iPad Pro 9.7-inch','iPad Air 13-inch (M3)','iPad Air 11-inch (M3)','iPad Air 13-inch (M2)','iPad Air 11-inch (M2)','iPad Air (5th generation)','iPad Air (4th generation)','iPad Air (3rd generation)','iPad Air 2','iPad Air (1st generation)','iPad (10th generation)','iPad (9th generation)','iPad (8th generation)','iPad (7th generation)','iPad (6th generation)','iPad (5th generation)','iPad mini (6th generation)','iPad mini (5th generation)','iPad mini 4','iPad mini 3','iPad mini 2']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'iphone',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Samsung') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Samsung','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Galaxy S26 Ultra','Galaxy S26+','Galaxy S26','Galaxy S26 FE','Galaxy S25 Ultra','Galaxy S25+','Galaxy S25','Galaxy S25 Edge','Galaxy S25 FE','Galaxy S24 Ultra','Galaxy S24+','Galaxy S24','Galaxy S24 FE','Galaxy S23 Ultra','Galaxy S23+','Galaxy S23','Galaxy S23 FE','Galaxy S22 Ultra','Galaxy S22+','Galaxy S22','Galaxy S21 Ultra','Galaxy S21+','Galaxy S21','Galaxy S21 FE','Galaxy S20 Ultra','Galaxy S20+','Galaxy S20','Galaxy S20 FE','Galaxy Note20 Ultra','Galaxy Note20','Galaxy Note10+','Galaxy Note10','Galaxy Z Fold8','Galaxy Z Fold8 Ultra','Galaxy Z Flip8','Galaxy Z Fold7','Galaxy Z Flip7','Galaxy Z Fold6','Galaxy Z Flip6','Galaxy Z Fold5','Galaxy Z Flip5','Galaxy Z Fold4','Galaxy Z Flip4','Galaxy Z Fold3','Galaxy Z Flip3','Galaxy A56 5G','Galaxy A55 5G','Galaxy A54 5G','Galaxy A53 5G','Galaxy A52','Galaxy A36 5G','Galaxy A35 5G','Galaxy A34 5G','Galaxy A33 5G','Galaxy A27 5G','Galaxy A26 5G','Galaxy A25 5G','Galaxy A24','Galaxy A23','Galaxy A17 5G','Galaxy A16 5G','Galaxy A15 5G','Galaxy A14 5G','Galaxy A13','Galaxy A06','Galaxy A05s','Galaxy A05','Galaxy M55','Galaxy M54','Galaxy M34','Galaxy M14']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Huawei') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Huawei','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Pura 80 Ultra','Pura 80 Pro','Pura 80','Pura 70 Ultra','Pura 70 Pro+','Pura 70 Pro','Pura 70','P60 Pro','P60','P50 Pro','P50','P40 Pro+','P40 Pro','P40','P30 Pro','P30','P20 Pro','P20','Mate 70 Pro+','Mate 70 Pro','Mate 70','Mate 60 Pro+','Mate 60 Pro','Mate 60','Mate 50 Pro','Mate 50','Mate 40 Pro','Mate 40','Mate 30 Pro','Mate 30','nova 14 Ultra','nova 14 Pro','nova 14','nova 13 Pro','nova 13','nova 12 Ultra','nova 12 Pro','nova 12','nova 11 Pro','nova 11','nova 10 Pro','nova 10','nova 9','nova 8','Enjoy 70','Enjoy 60']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Vivo') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Vivo','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['X200 Ultra','X200 Pro','X200','X100 Ultra','X100 Pro','X100','X90 Pro+','X90 Pro','X90','X80 Pro','X80','V60','V50','V40 Pro','V40','V30 Pro','V30','V29','V27 Pro','V27','V25 Pro','V25','Y300 Pro','Y300','Y200 Pro','Y200','Y100','Y78','Y77','Y36','Y35','Y28','Y27','Y22','Y21','Y20']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Oppo') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Oppo','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Find X8 Ultra','Find X8 Pro','Find X8','Find X7 Ultra','Find X7','Find X6 Pro','Find X6','Find X5 Pro','Find X5','Find N5','Find N3','Find N3 Flip','Find N2','Find N2 Flip','Reno14 Pro','Reno14','Reno13 Pro','Reno13','Reno12 Pro','Reno12','Reno11 Pro','Reno11','Reno10 Pro+','Reno10 Pro','Reno10','Reno8 Pro','Reno8','Reno7 Pro','Reno7','A5 Pro','A3 Pro','A3','A98','A78','A77','A60','A58','A57','A38','A18','A17','A16']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Xiaomi') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Xiaomi','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Xiaomi 15 Ultra','Xiaomi 15 Pro','Xiaomi 15','Xiaomi 14 Ultra','Xiaomi 14 Pro','Xiaomi 14','Xiaomi 13 Ultra','Xiaomi 13 Pro','Xiaomi 13','Xiaomi 12S Ultra','Xiaomi 12 Pro','Xiaomi 12','Xiaomi 11 Ultra','Xiaomi 11T Pro','Xiaomi 11T','Xiaomi 11','Xiaomi Mi 10 Ultra','Xiaomi Mi 10 Pro','Xiaomi Mi 10','Xiaomi MIX Flip','Xiaomi MIX Fold 4','Xiaomi MIX Fold 3','Xiaomi MIX Fold 2','Xiaomi Civi 5 Pro','Xiaomi Civi 4 Pro','Xiaomi Civi 3','Xiaomi 15T Pro','Xiaomi 15T','Xiaomi 14T Pro','Xiaomi 14T','Xiaomi 13T Pro','Xiaomi 13T']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Redmi') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Redmi','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Redmi Note 14 Pro+ 5G','Redmi Note 14 Pro 5G','Redmi Note 14 5G','Redmi Note 14','Redmi Note 13 Pro+ 5G','Redmi Note 13 Pro 5G','Redmi Note 13 5G','Redmi Note 13','Redmi Note 12 Pro+ 5G','Redmi Note 12 Pro 5G','Redmi Note 12 5G','Redmi Note 12','Redmi Note 11 Pro+ 5G','Redmi Note 11 Pro 5G','Redmi Note 11','Redmi Note 10 Pro','Redmi Note 10','Redmi K80 Ultra','Redmi K80 Pro','Redmi K80','Redmi K70 Ultra','Redmi K70 Pro','Redmi K70','Redmi 14C','Redmi 13C','Redmi 13','Redmi 12C','Redmi 12','Redmi 10C','Redmi 10']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Tecno') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Tecno','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Phantom V Fold2','Phantom V Flip2','Phantom V Fold','Phantom V Flip','Camon 40 Premier 5G','Camon 40 Pro 5G','Camon 40 Pro','Camon 40','Camon 30 Premier 5G','Camon 30 Pro 5G','Camon 30 5G','Camon 30','Camon 20 Premier 5G','Camon 20 Pro 5G','Camon 20 Pro','Camon 20','Pova 7 Ultra 5G','Pova 7 Pro 5G','Pova 7 5G','Pova 7','Pova 6 Pro 5G','Pova 6','Spark 40 Pro+','Spark 40 Pro','Spark 40','Spark 30 Pro','Spark 30 5G','Spark 30','Spark 20 Pro+','Spark 20 Pro','Spark 20','Spark Go 1']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
  select id into v_brand_id from public.brands where lower(name)=lower('Infinix') and (category='phone' or category is null) order by case when category='phone' then 0 else 1 end limit 1;
  if v_brand_id is null then insert into public.brands(name,category,is_active) values ('Infinix','phone',true) returning id into v_brand_id; else update public.brands set is_active=true where id=v_brand_id; end if;
  foreach v_name in array array['Zero 40 5G','Zero 40','Zero 30 5G','Zero 30','Zero Ultra','GT 30 Pro','GT 20 Pro','GT 10 Pro','Note 50 Pro+ 5G','Note 50 Pro','Note 50','Note 40 Pro+ 5G','Note 40 Pro 5G','Note 40 Pro','Note 40','Note 30 Pro','Note 30 5G','Note 30','Hot 60 Pro+','Hot 60 Pro','Hot 60 5G','Hot 50 Pro+','Hot 50 Pro','Hot 50 5G','Hot 50','Hot 40 Pro','Hot 40','Smart 10 Plus','Smart 10','Smart 9 HD','Smart 9']::text[] loop
    select id into v_model_id from public.product_models where brand_id=v_brand_id and category='phone' and lower(name)=lower(v_name) limit 1;
    if v_model_id is null then insert into public.product_models(brand_id,category,name,phone_platform,is_active) values (v_brand_id,'phone',v_name,'android',true) returning id into v_model_id; else update public.product_models set is_active=true where id=v_model_id; end if;
    insert into public.phone_model_specs(product_model_id,colors,storage_options_gb,imei_count) values (v_model_id,array['Black','White','Blue','Gray']::text[],array[64,128,256,512]::integer[],2) on conflict(product_model_id) do nothing;
  end loop;
end $$;